# Generated by Django 5.0.3 on 2024-05-02 02:59

import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=64)),
                ('street_address', models.CharField(max_length=128, verbose_name='address')),
                ('city', models.CharField(max_length=64)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website', models.URLField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Bowling Center',
                'ordering': ['state', 'center_name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email_address', models.EmailField(max_length=128)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('director_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament Director',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('flyer', models.FileField(blank=True, upload_to='tournament_flyers')),
                ('website', models.URLField(blank=True, max_length=256)),
                ('bowling_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentfinder.bowlingcenter')),
                ('tournament_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentfinder.tournamentdirector')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
